import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  fullContainer: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 12,
    paddingBottom: 56,
    backgroundColor: "#fff",
  },
  selectorRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
    gap: 8,
    flexWrap: "wrap" as any,
    position: "relative",
    zIndex: 100000,
    elevation: 60,
  },
  storeButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginHorizontal: 6,
    borderRadius: 8,
    backgroundColor: "#fff",
    borderColor: "#e6e6e6",
    borderWidth: 1,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  storeButtonActive: { backgroundColor: "#007bff" },
  storeButtonText: { color: "#333", fontWeight: "600" },
  storeButtonTextActive: { color: "#fff" },
  mapContainer: {
    flex: 1,
    alignSelf: "stretch",
    marginHorizontal: 6,
    minHeight: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    borderRadius: 0,
    overflow: "visible",
  },
  infoRow: {
    padding: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dimText: { fontWeight: "600" },
  smallButton: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4 },
  routeControls: { flexDirection: "row", alignItems: "center", marginLeft: 8 },
  routeInput: {
    backgroundColor: "#fff",
    borderColor: "#e9e9e9",
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginHorizontal: 6,
    borderRadius: 6,
    minWidth: 80,
  },
  routeButton: { marginLeft: 6 },
  directionsPanel: { padding: 8, borderTopWidth: 1, borderTopColor: "#eee" },
  directionItem: { paddingVertical: 4 },
  mapRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: Platform.OS === 'web' ? 6 : 8,
    paddingTop: 12,
    marginBottom: 56,
    width: "100%",
  },
  sidePanel: {
    width: 320,
    maxWidth: 420,
    alignSelf: "flex-start",
    padding: 12,
    borderLeftWidth: 1,
    borderLeftColor: "#f3f3f3",
    backgroundColor: "#fafafa",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    marginBottom: 56,
    marginRight: Platform.OS === 'web' ? 80 : 16,
  },
  // zone detail card styles
  zoneCard: {
    backgroundColor: "#fff",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: "#eee",
    overflow: "hidden",
  },
  zoneCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f3f3",
    backgroundColor: "#fafcff",
  },
  zoneCardTitle: { fontWeight: "700", fontSize: 16 },
  zoneCardClose: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: "#fff",
    borderColor: "#e9e9e9",
    borderWidth: 1,
  },
  zoneCardCloseText: { color: "#333", fontWeight: "600" },
  zoneCardBody: { maxHeight: 520, padding: 12, backgroundColor: "#fff" },
});
