@startuml
' Domain Model DDD for the Commerce Prototype

entity Product {
  + Id: string
  + Name: string
  + PriceId: string
  + CategoryId: string
  + StockId: string
  + Description: string
  + CreationDate: DateTime
  + Images: List<ImageId>
}

entity Stock {
    + Id: string
    + ColorId: string
    + SizeId: string
    + Quantity: int
}

entity Color {
  + Id: string
  + Name: string
}

entity Size {
  + Id: string
  + Name: string
}

entity Price {
  + Id: string
  + Amount: decimal
  + Currency: string
}

entity Category {
  +Id: string
  +Name: string
}

entity Image {
  + Id: string
  + Name: string
  + Url: string
}

Product }o--|| Category : belongs to
Product }o--|| Price : has
Product }o--|| Stock : has
Product }o--o{ Image : has
Stock }o--|| Color : has
Stock }o--|| Size : has

@enduml
